spring:
  datasource:
    url: jdbc:oracle:thin:@svuxddb3.gvt.net.br:1521:dint
    username: SQLUTIL_OWNER
    password: QV2654_N
    driver:
      class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 200MB
      max-request-size: 210MB
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  error:
    include-stacktrace: never
file:    #prefix no fileConfig
  upload-dir: C:/OSS/Projetos/UploadDir #Diretorio para salvar os arquivos