spring.datasource.url=jdbc:oracle:thin:@svuxddb3.gvt.net.br:1521:dint
spring.datasource.username=SQLUTIL_OWNER
spring.datasource.password=QV2654_N
spring.datasource.driver.class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

server.error.include-stacktrace=never